# Generated by Django 3.0.8 on 2021-01-05 07:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Model', models.CharField(blank=True, max_length=255, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAlarmReceived', models.DateField(blank=True, null=True)),
                ('TimeAlarmReceived', models.TimeField(blank=True, null=True)),
                ('Caller', models.CharField(blank=True, max_length=255, null=True)),
                ('CallerAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('HouseNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('Street', models.CharField(blank=True, max_length=255, null=True)),
                ('Location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('OccupancyType', models.CharField(blank=True, choices=[('Structural/Residential', 'Structural/Residential'), ('Non Structural', 'Non Structural'), ('Vehicular', 'Vehicular')], max_length=255, null=True)),
                ('OccupancyTypeRemarks', models.CharField(blank=True, max_length=255, null=True)),
                ('DistanceFromBase', models.IntegerField(default=0)),
                ('DescriptionOfStructure', models.TextField(blank=True, null=True)),
                ('InjuredCivilianM', models.IntegerField(default=0)),
                ('InjuredCivilianF', models.IntegerField(default=0)),
                ('InjuredFireFighterM', models.IntegerField(default=0)),
                ('InjuredFireFighterF', models.IntegerField(default=0)),
                ('DeathCivilianM', models.IntegerField(default=0)),
                ('DeathCivilianF', models.IntegerField(default=0)),
                ('DeathFireFighterM', models.IntegerField(default=0)),
                ('DeathFireFighterF', models.IntegerField(default=0)),
                ('Details', tinymce.models.HTMLField(blank=True, null=True)),
                ('Problems', tinymce.models.HTMLField(blank=True, null=True)),
                ('Observations', tinymce.models.HTMLField(blank=True, null=True)),
                ('OwnerName', models.CharField(blank=True, max_length=255, null=True)),
                ('Occupant', models.CharField(blank=True, max_length=255, null=True)),
                ('EstablishmentName', models.CharField(blank=True, max_length=255, null=True)),
                ('EstimatedDamageCost', models.IntegerField(default=0)),
                ('FinalDamageCost', models.IntegerField(default=0)),
                ('Involved', models.CharField(blank=True, max_length=255, null=True)),
                ('InvestigationDetails', tinymce.models.HTMLField(blank=True, null=True)),
                ('Disposition', tinymce.models.HTMLField(blank=True, null=True)),
                ('Origin', models.CharField(blank=True, max_length=255, null=True)),
                ('Cause', models.CharField(blank=True, max_length=255, null=True)),
                ('TimeStarted', models.TimeField(blank=True, null=True)),
                ('Alarm', models.CharField(blank=True, choices=[('1st Alarm', '1st Alarm'), ('2nd Alarm', '2nd Alarm'), ('3rd Alarm', '3rd Alarm'), ('4th Alarm', '4th Alarm'), ('5th Alarm', '5th Alarm'), ('Task Force Alpha', 'Task Force Alpha'), ('Task Force Bravo', 'Task Force Bravo'), ('Task Force Charlie', 'Task Force Charlie'), ('Task Force Delta', 'Task Force Delta'), ('Task Force Echo', 'Task Foce Echo'), ('Task Force Hotel', 'Task Force Hotel'), ('Task Force India', 'Task Force India'), ('General Alarm', 'General Alarm')], max_length=100, null=True)),
                ('DateTimeUnderControl', models.DateTimeField(blank=True, null=True)),
                ('DateTimeFireOut', models.DateTimeField(blank=True, null=True)),
                ('Remarks', models.CharField(blank=True, choices=[('closed', 'Closed'), ('under investigation', 'Under Investigation'), ('', '')], default='closed', max_length=255)),
                ('Approved', models.BooleanField(default=False)),
            ],
        ),
    ]
