# Generated by Django 3.0.8 on 2021-01-21 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210105_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breathingapparatus',
            name='Incident',
        ),
        migrations.RemoveField(
            model_name='dutypersonnel',
            name='Incident',
        ),
        migrations.RemoveField(
            model_name='dutypersonnel',
            name='Personnel',
        ),
        migrations.RemoveField(
            model_name='extinguisingagent',
            name='Incident',
        ),
        migrations.RemoveField(
            model_name='hoseline',
            name='Incident',
        ),
        migrations.AlterUniqueTogether(
            name='incidentresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='incidentresponse',
            name='Engine',
        ),
        migrations.RemoveField(
            model_name='incidentresponse',
            name='Incident',
        ),
        migrations.RemoveField(
            model_name='ropeandladder',
            name='Incident',
        ),
        migrations.RemoveField(
            model_name='station',
            name='ChiefOfficer',
        ),
        migrations.AlterUniqueTogether(
            name='timealarmstatus',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='timealarmstatus',
            name='Incident',
        ),
        migrations.DeleteModel(
            name='AlarmStatusUponArrival',
        ),
        migrations.DeleteModel(
            name='BreathingApparatus',
        ),
        migrations.DeleteModel(
            name='DutyPersonnel',
        ),
        migrations.DeleteModel(
            name='ExtinguisingAgent',
        ),
        migrations.DeleteModel(
            name='HoseLine',
        ),
        migrations.DeleteModel(
            name='IncidentResponse',
        ),
        migrations.DeleteModel(
            name='RopeAndLadder',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='TimeAlarmStatus',
        ),
    ]
