# Generated by Django 3.0.8 on 2021-01-05 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20210105_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Model', models.CharField(blank=True, max_length=255, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=100, null=True)),
                ('MiddleName', models.CharField(blank=True, max_length=100, null=True)),
                ('LastName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=100, unique=True)),
                ('Definition', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='barangay',
            options={'ordering': ('Name',)},
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, max_length=255)),
                ('TelephoneNumber', models.CharField(blank=True, max_length=255)),
                ('PhoneNumbers', models.CharField(blank=True, max_length=255)),
                ('EmailAddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('BFPLogo', models.ImageField(blank=True, null=True, upload_to='')),
                ('StationLogo', models.ImageField(blank=True, null=True, upload_to='')),
                ('ChiefOfficer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_bfp', to='home.Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='RopeAndLadder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=255)),
                ('Length', models.IntegerField(default=0)),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='Rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Rank'),
        ),
        migrations.CreateModel(
            name='HoseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nr', models.IntegerField(default=0)),
                ('Type', models.CharField(blank=True, max_length=255)),
                ('Length', models.IntegerField(default=0)),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident')),
            ],
        ),
        migrations.CreateModel(
            name='ExtinguisingAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('Type', models.CharField(blank=True, max_length=255)),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=100)),
                ('Rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Rank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DutyPersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(blank=True, max_length=255)),
                ('Remarks', models.CharField(blank=True, max_length=255)),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident')),
                ('Personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='BreathingApparatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BreathingApparatusNr', models.IntegerField(default=0)),
                ('BreathingApparatusType', models.CharField(blank=True, max_length=255, null=True)),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='Investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_investigator', to='home.Personnel'),
        ),
        migrations.AddField(
            model_name='incident',
            name='PersonnelReceivingCall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Personnel'),
        ),
        migrations.CreateModel(
            name='TimeAlarmStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlarmStatus', models.CharField(blank=True, choices=[('1st Alarm', '1st Alarm'), ('2nd Alarm', '2nd Alarm'), ('3rd Alarm', '3rd Alarm'), ('4th Alarm', '4th Alarm'), ('5th Alarm', '5th Alarm'), ('Task Force Alpha', 'Task Force Alpha'), ('Task Force Bravo', 'Task Force Bravo'), ('Task Force Charlie', 'Task Force Charlie'), ('Task Force Delta', 'Task Force Delta'), ('Task Force Echo', 'Task Foce Echo'), ('Task Force Hotel', 'Task Force Hotel'), ('Task Force India', 'Task Force India'), ('General Alarm', 'General Alarm')], default='', max_length=255)),
                ('AlarmTime', models.TimeField(blank=True, null=True)),
                ('GroundCommander', models.CharField(blank=True, max_length=255)),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident')),
            ],
            options={
                'unique_together': {('Incident', 'AlarmStatus')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='personnel',
            unique_together={('FirstName', 'LastName')},
        ),
        migrations.CreateModel(
            name='IncidentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeDispatched', models.TimeField(blank=True, null=True)),
                ('TimeArrived', models.TimeField(blank=True, null=True)),
                ('TimeReturnedToBase', models.TimeField(blank=True, null=True)),
                ('WaterTankRefilled', models.IntegerField(default=0)),
                ('GasConsumed', models.IntegerField(default=0)),
                ('Engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Engines')),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident')),
            ],
            options={
                'unique_together': {('Incident', 'Engine')},
            },
        ),
        migrations.CreateModel(
            name='AlarmStatusUponArrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusUponArrival', models.CharField(blank=True, choices=[('1st Alarm', '1st Alarm'), ('2nd Alarm', '2nd Alarm'), ('3rd Alarm', '3rd Alarm'), ('4th Alarm', '4th Alarm'), ('5th Alarm', '5th Alarm'), ('Task Force Alpha', 'Task Force Alpha'), ('Task Force Bravo', 'Task Force Bravo'), ('Task Force Charlie', 'Task Force Charlie'), ('Task Force Delta', 'Task Force Delta'), ('Task Force Echo', 'Task Foce Echo'), ('Task Force Hotel', 'Task Force Hotel'), ('Task Force India', 'Task Force India'), ('General Alarm', 'General Alarm')], default='', max_length=255)),
                ('StatusUponArrivalRemarks', models.CharField(blank=True, max_length=255)),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident')),
            ],
            options={
                'unique_together': {('Incident', 'StatusUponArrival')},
            },
        ),
    ]
