# Generated by Django 3.0.8 on 2021-01-21 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210122_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, max_length=255)),
                ('TelephoneNumber', models.CharField(blank=True, max_length=255)),
                ('PhoneNumbers', models.CharField(blank=True, max_length=255)),
                ('EmailAddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('BFPLogo', models.ImageField(blank=True, null=True, upload_to='')),
                ('StationLogo', models.ImageField(blank=True, null=True, upload_to='')),
                ('ChiefOfficer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_bfp', to='home.Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='DutyPersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(blank=True, max_length=255)),
                ('Remarks', models.CharField(blank=True, max_length=255)),
                ('Incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Incident')),
                ('Personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Personnel')),
            ],
        ),
    ]
